# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.4.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opensilexClientToolsPython
from opensilexClientToolsPython.models.api_license_info_dto import ApiLicenseInfoDTO  # noqa: E501
from opensilexClientToolsPython.rest import ApiException


class TestApiLicenseInfoDTO(unittest.TestCase):
    """ApiLicenseInfoDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiLicenseInfoDTO(self):
        """Test ApiLicenseInfoDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilexClientToolsPython.models.api_license_info_dto.ApiLicenseInfoDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
