# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.00-rc+5.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opensilexClientToolsPython
from opensilexClientToolsPython.models.infrastructure_facility_update_dto import InfrastructureFacilityUpdateDTO
from opensilexClientToolsPython.rest import ApiException


class TestInfrastructureFacilityUpdateDTO(unittest.TestCase):
    """InfrastructureFacilityUpdateDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInfrastructureFacilityUpdateDTO(self):
        """Test InfrastructureFacilityUpdateDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilexClientToolsPython.models.infrastructure_facility_update_dto.InfrastructureFacilityUpdateDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
