# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0-rc+5.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opensilexClientToolsPython
from opensilexClientToolsPython.models.season import Season
from opensilexClientToolsPython.rest import ApiException


class TestSeason(unittest.TestCase):
    """Season unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSeason(self):
        """Test Season"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilexClientToolsPython.models.season.Season()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
