# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.3.0-rdg
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opensilexClientToolsPython
from opensilexClientToolsPython.models.site_get_list_dto import SiteGetListDTO
from opensilexClientToolsPython.rest import ApiException


class TestSiteGetListDTO(unittest.TestCase):
    """SiteGetListDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSiteGetListDTO(self):
        """Test SiteGetListDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilexClientToolsPython.models.site_get_list_dto.SiteGetListDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
