# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0-rc+5.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opensilexClientToolsPython
from opensilexClientToolsPython.models.infrastructure_get_dto import InfrastructureGetDTO
from opensilexClientToolsPython.rest import ApiException


class TestInfrastructureGetDTO(unittest.TestCase):
    """InfrastructureGetDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInfrastructureGetDTO(self):
        """Test InfrastructureGetDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilexClientToolsPython.models.infrastructure_get_dto.InfrastructureGetDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
