# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: INSTANCE-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opensilexClientToolsPython
from opensilexClientToolsPython.api.mobile_api import MobileApi  # noqa: E501
from opensilexClientToolsPython.rest import ApiException


class TestMobileApi(unittest.TestCase):
    """MobileApi unit test stubs"""

    def setUp(self):
        self.api = opensilexClientToolsPython.api.mobile_api.MobileApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_form(self):
        """Test case for create_form

        Add a form  # noqa: E501
        """
        pass

    def test_delete_form(self):
        """Test case for delete_form

        Delete form  # noqa: E501
        """
        pass

    def test_search_form_list(self):
        """Test case for search_form_list

        Search forms  # noqa: E501
        """
        pass

    def test_update1(self):
        """Test case for update1

        Update form  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
