# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opensilexClientToolsPython
from opensilexClientToolsPython.models.sparql_model_relation import SPARQLModelRelation
from opensilexClientToolsPython.rest import ApiException


class TestSPARQLModelRelation(unittest.TestCase):
    """SPARQLModelRelation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSPARQLModelRelation(self):
        """Test SPARQLModelRelation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilexClientToolsPython.models.sparql_model_relation.SPARQLModelRelation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
