# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: INSTANCE-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opensilexClientToolsPython
from opensilexClientToolsPython.models.device_get_dto import DeviceGetDTO  # noqa: E501
from opensilexClientToolsPython.rest import ApiException


class TestDeviceGetDTO(unittest.TestCase):
    """DeviceGetDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeviceGetDTO(self):
        """Test DeviceGetDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilexClientToolsPython.models.device_get_dto.DeviceGetDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
