# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0-rc+7.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opensilexClientToolsPython
from opensilexClientToolsPython.models.csv_validation_dto import CSVValidationDTO
from opensilexClientToolsPython.rest import ApiException


class TestCSVValidationDTO(unittest.TestCase):
    """CSVValidationDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCSVValidationDTO(self):
        """Test CSVValidationDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilexClientToolsPython.models.csv_validation_dto.CSVValidationDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
