# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: INSTANCE-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opensilexClientToolsPython
from opensilexClientToolsPython.models.data_provenance_model import DataProvenanceModel  # noqa: E501
from opensilexClientToolsPython.rest import ApiException


class TestDataProvenanceModel(unittest.TestCase):
    """DataProvenanceModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataProvenanceModel(self):
        """Test DataProvenanceModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilexClientToolsPython.models.data_provenance_model.DataProvenanceModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
