# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.3.2-rdg
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opensilexClientToolsPython
from opensilexClientToolsPython.models.named_resource_dto_site_model import NamedResourceDTOSiteModel
from opensilexClientToolsPython.rest import ApiException


class TestNamedResourceDTOSiteModel(unittest.TestCase):
    """NamedResourceDTOSiteModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNamedResourceDTOSiteModel(self):
        """Test NamedResourceDTOSiteModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilexClientToolsPython.models.named_resource_dto_site_model.NamedResourceDTOSiteModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
