# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.2.0-rdg
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opensilexClientToolsPython
from opensilexClientToolsPython.models.br_ap_iv1_observation_unit_list_response import BrAPIv1ObservationUnitListResponse
from opensilexClientToolsPython.rest import ApiException


class TestBrAPIv1ObservationUnitListResponse(unittest.TestCase):
    """BrAPIv1ObservationUnitListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBrAPIv1ObservationUnitListResponse(self):
        """Test BrAPIv1ObservationUnitListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilexClientToolsPython.models.br_ap_iv1_observation_unit_list_response.BrAPIv1ObservationUnitListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
