# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.4.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opensilexClientToolsPython
from opensilexClientToolsPython.models.ontology_agroportal_dto import OntologyAgroportalDTO  # noqa: E501
from opensilexClientToolsPython.rest import ApiException


class TestOntologyAgroportalDTO(unittest.TestCase):
    """OntologyAgroportalDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOntologyAgroportalDTO(self):
        """Test OntologyAgroportalDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilexClientToolsPython.models.ontology_agroportal_dto.OntologyAgroportalDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
