# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.4.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opensilexClientToolsPython
from opensilexClientToolsPython.models.scientific_object_export_dto import ScientificObjectExportDTO  # noqa: E501
from opensilexClientToolsPython.rest import ApiException


class TestScientificObjectExportDTO(unittest.TestCase):
    """ScientificObjectExportDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScientificObjectExportDTO(self):
        """Test ScientificObjectExportDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilexClientToolsPython.models.scientific_object_export_dto.ScientificObjectExportDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
