# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: INSTANCE-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opensilexClientToolsPython
from opensilexClientToolsPython.api.annotations_api import AnnotationsApi  # noqa: E501
from opensilexClientToolsPython.rest import ApiException


class TestAnnotationsApi(unittest.TestCase):
    """AnnotationsApi unit test stubs"""

    def setUp(self):
        self.api = opensilexClientToolsPython.api.annotations_api.AnnotationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_count_annotations(self):
        """Test case for count_annotations

        Count annotations  # noqa: E501
        """
        pass

    def test_create_annotation(self):
        """Test case for create_annotation

        Create an annotation  # noqa: E501
        """
        pass

    def test_delete_annotation(self):
        """Test case for delete_annotation

        Delete an annotation  # noqa: E501
        """
        pass

    def test_get_annotation(self):
        """Test case for get_annotation

        Get an annotation  # noqa: E501
        """
        pass

    def test_search_annotations(self):
        """Test case for search_annotations

        Search annotations  # noqa: E501
        """
        pass

    def test_search_motivations(self):
        """Test case for search_motivations

        Search motivations  # noqa: E501
        """
        pass

    def test_update_annotation(self):
        """Test case for update_annotation

        Update an annotation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
