# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.2.0-rdg
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opensilexClientToolsPython
from opensilexClientToolsPython.models.facility_named_dto import FacilityNamedDTO
from opensilexClientToolsPython.rest import ApiException


class TestFacilityNamedDTO(unittest.TestCase):
    """FacilityNamedDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFacilityNamedDTO(self):
        """Test FacilityNamedDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilexClientToolsPython.models.facility_named_dto.FacilityNamedDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
