# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0-rc+7.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opensilexClientToolsPython
from opensilexClientToolsPython.models.scientific_object_creation_dto import ScientificObjectCreationDTO
from opensilexClientToolsPython.rest import ApiException


class TestScientificObjectCreationDTO(unittest.TestCase):
    """ScientificObjectCreationDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScientificObjectCreationDTO(self):
        """Test ScientificObjectCreationDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilexClientToolsPython.models.scientific_object_creation_dto.ScientificObjectCreationDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
