# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opensilexClientToolsPython
from opensilexClientToolsPython.models.capabilities import Capabilities
from opensilexClientToolsPython.rest import ApiException


class TestCapabilities(unittest.TestCase):
    """Capabilities unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCapabilities(self):
        """Test Capabilities"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilexClientToolsPython.models.capabilities.Capabilities()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
