# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.4.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opensilexClientToolsPython
from opensilexClientToolsPython.models.brapi_data_response_part_list_faidarev1_trial_dto import BrapiDataResponsePartListFaidarev1TrialDTO  # noqa: E501
from opensilexClientToolsPython.rest import ApiException


class TestBrapiDataResponsePartListFaidarev1TrialDTO(unittest.TestCase):
    """BrapiDataResponsePartListFaidarev1TrialDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBrapiDataResponsePartListFaidarev1TrialDTO(self):
        """Test BrapiDataResponsePartListFaidarev1TrialDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilexClientToolsPython.models.brapi_data_response_part_list_faidarev1_trial_dto.BrapiDataResponsePartListFaidarev1TrialDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
