# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: INSTANCE-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opensilexClientToolsPython
from opensilexClientToolsPython.models.unit_creation_dto import UnitCreationDTO
from opensilexClientToolsPython.rest import ApiException


class TestUnitCreationDTO(unittest.TestCase):
    """UnitCreationDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnitCreationDTO(self):
        """Test UnitCreationDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilexClientToolsPython.models.unit_creation_dto.UnitCreationDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
