# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: INSTANCE-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opensilexClientToolsPython
from opensilexClientToolsPython.models.concerned_item_position_creation_dto import ConcernedItemPositionCreationDTO  # noqa: E501
from opensilexClientToolsPython.rest import ApiException


class TestConcernedItemPositionCreationDTO(unittest.TestCase):
    """ConcernedItemPositionCreationDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConcernedItemPositionCreationDTO(self):
        """Test ConcernedItemPositionCreationDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilexClientToolsPython.models.concerned_item_position_creation_dto.ConcernedItemPositionCreationDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
