# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opensilexClientToolsPython
from opensilexClientToolsPython.models.count_item_period_dto import CountItemPeriodDTO
from opensilexClientToolsPython.rest import ApiException


class TestCountItemPeriodDTO(unittest.TestCase):
    """CountItemPeriodDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCountItemPeriodDTO(self):
        """Test CountItemPeriodDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilexClientToolsPython.models.count_item_period_dto.CountItemPeriodDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
