# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: INSTANCE-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opensilexClientToolsPython
from opensilexClientToolsPython.models.group_user_profile_model import GroupUserProfileModel  # noqa: E501
from opensilexClientToolsPython.rest import ApiException


class TestGroupUserProfileModel(unittest.TestCase):
    """GroupUserProfileModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGroupUserProfileModel(self):
        """Test GroupUserProfileModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilexClientToolsPython.models.group_user_profile_model.GroupUserProfileModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
