# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.4.9
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opensilexClientToolsPython
from opensilexClientToolsPython.models.properties_by_domain_dto import PropertiesByDomainDTO  # noqa: E501
from opensilexClientToolsPython.rest import ApiException


class TestPropertiesByDomainDTO(unittest.TestCase):
    """PropertiesByDomainDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropertiesByDomainDTO(self):
        """Test PropertiesByDomainDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilexClientToolsPython.models.properties_by_domain_dto.PropertiesByDomainDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
