# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.4.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opensilexClientToolsPython
from opensilexClientToolsPython.models.account_get_dto import AccountGetDTO  # noqa: E501
from opensilexClientToolsPython.rest import ApiException


class TestAccountGetDTO(unittest.TestCase):
    """AccountGetDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountGetDTO(self):
        """Test AccountGetDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilexClientToolsPython.models.account_get_dto.AccountGetDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
