# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: BUILD-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opensilexClientToolsPython
from opensilexClientToolsPython.models.observation_treatment import ObservationTreatment
from opensilexClientToolsPython.rest import ApiException


class TestObservationTreatment(unittest.TestCase):
    """ObservationTreatment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testObservationTreatment(self):
        """Test ObservationTreatment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilexClientToolsPython.models.observation_treatment.ObservationTreatment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
