# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.2.0-rdg
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opensilexClientToolsPython
from opensilexClientToolsPython.models.br_ap_iv1_germplasm_dto import BrAPIv1GermplasmDTO
from opensilexClientToolsPython.rest import ApiException


class TestBrAPIv1GermplasmDTO(unittest.TestCase):
    """BrAPIv1GermplasmDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBrAPIv1GermplasmDTO(self):
        """Test BrAPIv1GermplasmDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilexClientToolsPython.models.br_ap_iv1_germplasm_dto.BrAPIv1GermplasmDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
