# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: INSTANCE-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opensilexClientToolsPython
from opensilexClientToolsPython.models.observation_unit_xref import ObservationUnitXref  # noqa: E501
from opensilexClientToolsPython.rest import ApiException


class TestObservationUnitXref(unittest.TestCase):
    """ObservationUnitXref unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testObservationUnitXref(self):
        """Test ObservationUnitXref"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilexClientToolsPython.models.observation_unit_xref.ObservationUnitXref()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
