# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0-rc+7.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opensilexClientToolsPython
from opensilexClientToolsPython.models.entity_details_dto import EntityDetailsDTO
from opensilexClientToolsPython.rest import ApiException


class TestEntityDetailsDTO(unittest.TestCase):
    """EntityDetailsDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntityDetailsDTO(self):
        """Test EntityDetailsDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilexClientToolsPython.models.entity_details_dto.EntityDetailsDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
