# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.3.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opensilexClientToolsPython
from opensilexClientToolsPython.models.faidarev1_call_dto import Faidarev1CallDTO
from opensilexClientToolsPython.rest import ApiException


class TestFaidarev1CallDTO(unittest.TestCase):
    """Faidarev1CallDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFaidarev1CallDTO(self):
        """Test Faidarev1CallDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilexClientToolsPython.models.faidarev1_call_dto.Faidarev1CallDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
