# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.4.9
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opensilexClientToolsPython
from opensilexClientToolsPython.models.rdf_property_get_dto import RDFPropertyGetDTO  # noqa: E501
from opensilexClientToolsPython.rest import ApiException


class TestRDFPropertyGetDTO(unittest.TestCase):
    """RDFPropertyGetDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRDFPropertyGetDTO(self):
        """Test RDFPropertyGetDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilexClientToolsPython.models.rdf_property_get_dto.RDFPropertyGetDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
