# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.4.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opensilexClientToolsPython
from opensilexClientToolsPython.models.factor_level_creation_dto import FactorLevelCreationDTO  # noqa: E501
from opensilexClientToolsPython.rest import ApiException


class TestFactorLevelCreationDTO(unittest.TestCase):
    """FactorLevelCreationDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFactorLevelCreationDTO(self):
        """Test FactorLevelCreationDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilexClientToolsPython.models.factor_level_creation_dto.FactorLevelCreationDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
