# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.4.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from typing import List, Dict


class CountListItemPeriodDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'total_difference_item_count': 'int',
        'difference_items': 'list[CountItemPeriodDTO]',
        'name': 'str',
        'type': 'str',
        'total_items_count': 'int',
        'items': 'list[CountItemDTO]'
    }

    attribute_map = {
        'total_difference_item_count': 'total_difference_item_count',
        'difference_items': 'difference_items',
        'name': 'name',
        'type': 'type',
        'total_items_count': 'total_items_count',
        'items': 'items'
    }
    def __init__(self,
        total_difference_item_count : 'int' = None,
        difference_items : 'List[CountItemPeriodDTO]' = None,
        name : 'str' = None,
        type : 'str' = None,
        total_items_count : 'int' = None,
        items : 'List[CountItemDTO]' = None):  # noqa: E501
        """CountListItemPeriodDTO - a model defined in Swagger"""  # noqa: E501

        self._total_difference_item_count = None
        self._difference_items = None
        self._name = None
        self._type = None
        self._total_items_count = None
        self._items = None
        self.discriminator = None

        if total_difference_item_count is not None:
            self.total_difference_item_count = total_difference_item_count
        if difference_items is not None:
            self.difference_items = difference_items
        if name is not None:
            self.name = name
        if type is not None:
            self.type = type
        if total_items_count is not None:
            self.total_items_count = total_items_count
        if items is not None:
            self.items = items

    @property
    def total_difference_item_count(self):
        """Gets the total_difference_item_count of this CountListItemPeriodDTO.  # noqa: E501


        :return: The total_difference_item_count of this CountListItemPeriodDTO.  # noqa: E501
        :rtype: int
        """
        return self._total_difference_item_count

    @total_difference_item_count.setter
    def total_difference_item_count(self, total_difference_item_count):
        """Sets the total_difference_item_count of this CountListItemPeriodDTO.


        :param total_difference_item_count: The total_difference_item_count of this CountListItemPeriodDTO.  # noqa: E501
        :type: int
        """

        self._total_difference_item_count = total_difference_item_count

    @property
    def difference_items(self):
        """Gets the difference_items of this CountListItemPeriodDTO.  # noqa: E501


        :return: The difference_items of this CountListItemPeriodDTO.  # noqa: E501
        :rtype: list[CountItemPeriodDTO]
        """
        return self._difference_items

    @difference_items.setter
    def difference_items(self, difference_items):
        """Sets the difference_items of this CountListItemPeriodDTO.


        :param difference_items: The difference_items of this CountListItemPeriodDTO.  # noqa: E501
        :type: list[CountItemPeriodDTO]
        """

        self._difference_items = difference_items

    @property
    def name(self):
        """Gets the name of this CountListItemPeriodDTO.  # noqa: E501


        :return: The name of this CountListItemPeriodDTO.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CountListItemPeriodDTO.


        :param name: The name of this CountListItemPeriodDTO.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def type(self):
        """Gets the type of this CountListItemPeriodDTO.  # noqa: E501


        :return: The type of this CountListItemPeriodDTO.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this CountListItemPeriodDTO.


        :param type: The type of this CountListItemPeriodDTO.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def total_items_count(self):
        """Gets the total_items_count of this CountListItemPeriodDTO.  # noqa: E501


        :return: The total_items_count of this CountListItemPeriodDTO.  # noqa: E501
        :rtype: int
        """
        return self._total_items_count

    @total_items_count.setter
    def total_items_count(self, total_items_count):
        """Sets the total_items_count of this CountListItemPeriodDTO.


        :param total_items_count: The total_items_count of this CountListItemPeriodDTO.  # noqa: E501
        :type: int
        """

        self._total_items_count = total_items_count

    @property
    def items(self):
        """Gets the items of this CountListItemPeriodDTO.  # noqa: E501


        :return: The items of this CountListItemPeriodDTO.  # noqa: E501
        :rtype: list[CountItemDTO]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this CountListItemPeriodDTO.


        :param items: The items of this CountListItemPeriodDTO.  # noqa: E501
        :type: list[CountItemDTO]
        """

        self._items = items

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CountListItemPeriodDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_api_formated_dict(self):
        """Returns a dict of properties as named in the API rather than in the model itself"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[self.attribute_map[attr]] = list(map(
                    lambda x: x.to_api_formated_dict() if hasattr(x, "to_api_formated_dict") else x,
                    value
                ))
            elif hasattr(value, "to_api_formated_dict"):
                result[self.attribute_map[attr]] = value.to_api_formated_dict()
            elif isinstance(value, dict):
                result[self.attribute_map[attr]] = dict(map(
                    lambda item: (item[0], item[1].to_api_formated_dict())
                    if hasattr(item[1], "to_api_formated_dict") else item,
                    value.items()
                ))
            else:
                result[self.attribute_map[attr]] = value
        if issubclass(CountListItemPeriodDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CountListItemPeriodDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
 

        
