# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from typing import List, Dict


class FacilityGetWithGeometryDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'description': 'str',
        'address': 'FacilityAddressDTO',
        'uri': 'str',
        'publisher': 'UserGetDTO',
        'publication_date': 'datetime',
        'last_updated_date': 'datetime',
        'rdf_type': 'str',
        'relations': 'list[RDFObjectRelationDTO]',
        'rdf_type_name': 'str',
        'geometry': 'GeoJsonObject'
    }

    attribute_map = {
        'name': 'name',
        'description': 'description',
        'address': 'address',
        'uri': 'uri',
        'publisher': 'publisher',
        'publication_date': 'publication_date',
        'last_updated_date': 'last_updated_date',
        'rdf_type': 'rdf_type',
        'relations': 'relations',
        'rdf_type_name': 'rdf_type_name',
        'geometry': 'geometry'
    }
    def __init__(self,
        name : 'str' = None,
        description : 'str' = None,
        address : 'FacilityAddressDTO' = None,
        uri : 'str' = None,
        publisher : 'UserGetDTO' = None,
        publication_date : 'datetime' = None,
        last_updated_date : 'datetime' = None,
        rdf_type : 'str' = None,
        relations : 'List[RDFObjectRelationDTO]' = None,
        rdf_type_name : 'str' = None,
        geometry : 'GeoJsonObject' = None):  # noqa: E501
        """FacilityGetWithGeometryDTO - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._description = None
        self._address = None
        self._uri = None
        self._publisher = None
        self._publication_date = None
        self._last_updated_date = None
        self._rdf_type = None
        self._relations = None
        self._rdf_type_name = None
        self._geometry = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if address is not None:
            self.address = address
        if uri is not None:
            self.uri = uri
        if publisher is not None:
            self.publisher = publisher
        if publication_date is not None:
            self.publication_date = publication_date
        if last_updated_date is not None:
            self.last_updated_date = last_updated_date
        if rdf_type is not None:
            self.rdf_type = rdf_type
        if relations is not None:
            self.relations = relations
        if rdf_type_name is not None:
            self.rdf_type_name = rdf_type_name
        if geometry is not None:
            self.geometry = geometry

    @property
    def name(self):
        """Gets the name of this FacilityGetWithGeometryDTO.  # noqa: E501


        :return: The name of this FacilityGetWithGeometryDTO.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this FacilityGetWithGeometryDTO.


        :param name: The name of this FacilityGetWithGeometryDTO.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this FacilityGetWithGeometryDTO.  # noqa: E501


        :return: The description of this FacilityGetWithGeometryDTO.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this FacilityGetWithGeometryDTO.


        :param description: The description of this FacilityGetWithGeometryDTO.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def address(self):
        """Gets the address of this FacilityGetWithGeometryDTO.  # noqa: E501


        :return: The address of this FacilityGetWithGeometryDTO.  # noqa: E501
        :rtype: FacilityAddressDTO
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this FacilityGetWithGeometryDTO.


        :param address: The address of this FacilityGetWithGeometryDTO.  # noqa: E501
        :type: FacilityAddressDTO
        """

        self._address = address

    @property
    def uri(self):
        """Gets the uri of this FacilityGetWithGeometryDTO.  # noqa: E501


        :return: The uri of this FacilityGetWithGeometryDTO.  # noqa: E501
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """Sets the uri of this FacilityGetWithGeometryDTO.


        :param uri: The uri of this FacilityGetWithGeometryDTO.  # noqa: E501
        :type: str
        """

        self._uri = uri

    @property
    def publisher(self):
        """Gets the publisher of this FacilityGetWithGeometryDTO.  # noqa: E501


        :return: The publisher of this FacilityGetWithGeometryDTO.  # noqa: E501
        :rtype: UserGetDTO
        """
        return self._publisher

    @publisher.setter
    def publisher(self, publisher):
        """Sets the publisher of this FacilityGetWithGeometryDTO.


        :param publisher: The publisher of this FacilityGetWithGeometryDTO.  # noqa: E501
        :type: UserGetDTO
        """

        self._publisher = publisher

    @property
    def publication_date(self):
        """Gets the publication_date of this FacilityGetWithGeometryDTO.  # noqa: E501


        :return: The publication_date of this FacilityGetWithGeometryDTO.  # noqa: E501
        :rtype: datetime
        """
        return self._publication_date

    @publication_date.setter
    def publication_date(self, publication_date):
        """Sets the publication_date of this FacilityGetWithGeometryDTO.


        :param publication_date: The publication_date of this FacilityGetWithGeometryDTO.  # noqa: E501
        :type: datetime
        """

        self._publication_date = publication_date

    @property
    def last_updated_date(self):
        """Gets the last_updated_date of this FacilityGetWithGeometryDTO.  # noqa: E501


        :return: The last_updated_date of this FacilityGetWithGeometryDTO.  # noqa: E501
        :rtype: datetime
        """
        return self._last_updated_date

    @last_updated_date.setter
    def last_updated_date(self, last_updated_date):
        """Sets the last_updated_date of this FacilityGetWithGeometryDTO.


        :param last_updated_date: The last_updated_date of this FacilityGetWithGeometryDTO.  # noqa: E501
        :type: datetime
        """

        self._last_updated_date = last_updated_date

    @property
    def rdf_type(self):
        """Gets the rdf_type of this FacilityGetWithGeometryDTO.  # noqa: E501


        :return: The rdf_type of this FacilityGetWithGeometryDTO.  # noqa: E501
        :rtype: str
        """
        return self._rdf_type

    @rdf_type.setter
    def rdf_type(self, rdf_type):
        """Sets the rdf_type of this FacilityGetWithGeometryDTO.


        :param rdf_type: The rdf_type of this FacilityGetWithGeometryDTO.  # noqa: E501
        :type: str
        """

        self._rdf_type = rdf_type

    @property
    def relations(self):
        """Gets the relations of this FacilityGetWithGeometryDTO.  # noqa: E501


        :return: The relations of this FacilityGetWithGeometryDTO.  # noqa: E501
        :rtype: list[RDFObjectRelationDTO]
        """
        return self._relations

    @relations.setter
    def relations(self, relations):
        """Sets the relations of this FacilityGetWithGeometryDTO.


        :param relations: The relations of this FacilityGetWithGeometryDTO.  # noqa: E501
        :type: list[RDFObjectRelationDTO]
        """

        self._relations = relations

    @property
    def rdf_type_name(self):
        """Gets the rdf_type_name of this FacilityGetWithGeometryDTO.  # noqa: E501


        :return: The rdf_type_name of this FacilityGetWithGeometryDTO.  # noqa: E501
        :rtype: str
        """
        return self._rdf_type_name

    @rdf_type_name.setter
    def rdf_type_name(self, rdf_type_name):
        """Sets the rdf_type_name of this FacilityGetWithGeometryDTO.


        :param rdf_type_name: The rdf_type_name of this FacilityGetWithGeometryDTO.  # noqa: E501
        :type: str
        """

        self._rdf_type_name = rdf_type_name

    @property
    def geometry(self):
        """Gets the geometry of this FacilityGetWithGeometryDTO.  # noqa: E501


        :return: The geometry of this FacilityGetWithGeometryDTO.  # noqa: E501
        :rtype: GeoJsonObject
        """
        return self._geometry

    @geometry.setter
    def geometry(self, geometry):
        """Sets the geometry of this FacilityGetWithGeometryDTO.


        :param geometry: The geometry of this FacilityGetWithGeometryDTO.  # noqa: E501
        :type: GeoJsonObject
        """

        self._geometry = geometry

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FacilityGetWithGeometryDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_api_formated_dict(self):
        """Returns a dict of properties as named in the API rather than in the model itself"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[self.attribute_map[attr]] = list(map(
                    lambda x: x.to_api_formated_dict() if hasattr(x, "to_api_formated_dict") else x,
                    value
                ))
            elif hasattr(value, "to_api_formated_dict"):
                result[self.attribute_map[attr]] = value.to_api_formated_dict()
            elif isinstance(value, dict):
                result[self.attribute_map[attr]] = dict(map(
                    lambda item: (item[0], item[1].to_api_formated_dict())
                    if hasattr(item[1], "to_api_formated_dict") else item,
                    value.items()
                ))
            else:
                result[self.attribute_map[attr]] = value
        if issubclass(FacilityGetWithGeometryDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FacilityGetWithGeometryDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
 

        
