# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.4.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from typing import List, Dict


class URIGlobalSearchDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'uri': 'str',
        'name': 'str',
        'context': 'str',
        '_property': 'bool',
        'rdf_type': 'str',
        'rdf_type_name': 'str',
        'rdfs_comment': 'str',
        'publisher': 'UserGetDTO',
        'publication_date': 'str',
        'last_updated_date': 'str',
        'super_types': 'URITypesDTO',
        'data_dto': 'DataGetSearchDTO',
        'datafile_dto': 'DataFileGetDTO',
        'root_class': 'str',
        'is_property': 'bool',
        'factor_uri': 'str'
    }

    attribute_map = {
        'uri': 'uri',
        'name': 'name',
        'context': 'context',
        '_property': 'property',
        'rdf_type': 'rdf_type',
        'rdf_type_name': 'rdf_type_name',
        'rdfs_comment': 'rdfs_comment',
        'publisher': 'publisher',
        'publication_date': 'publication_date',
        'last_updated_date': 'last_updated_date',
        'super_types': 'super_types',
        'data_dto': 'data_dto',
        'datafile_dto': 'datafile_dto',
        'root_class': 'root_class',
        'is_property': 'is_property',
        'factor_uri': 'factor_uri'
    }
    def __init__(self,
        uri : 'str' = None,
        name : 'str' = None,
        context : 'str' = None,
        _property : 'bool' = None,
        rdf_type : 'str' = None,
        rdf_type_name : 'str' = None,
        rdfs_comment : 'str' = None,
        publisher : 'UserGetDTO' = None,
        publication_date : 'str' = None,
        last_updated_date : 'str' = None,
        super_types : 'URITypesDTO' = None,
        data_dto : 'DataGetSearchDTO' = None,
        datafile_dto : 'DataFileGetDTO' = None,
        root_class : 'str' = None,
        is_property : 'bool' = None,
        factor_uri : 'str' = None):  # noqa: E501
        """URIGlobalSearchDTO - a model defined in Swagger"""  # noqa: E501

        self._uri = None
        self._name = None
        self._context = None
        self.__property = None
        self._rdf_type = None
        self._rdf_type_name = None
        self._rdfs_comment = None
        self._publisher = None
        self._publication_date = None
        self._last_updated_date = None
        self._super_types = None
        self._data_dto = None
        self._datafile_dto = None
        self._root_class = None
        self._is_property = None
        self._factor_uri = None
        self.discriminator = None

        if uri is not None:
            self.uri = uri
        if name is not None:
            self.name = name
        if context is not None:
            self.context = context
        if _property is not None:
            self._property = _property
        if rdf_type is not None:
            self.rdf_type = rdf_type
        if rdf_type_name is not None:
            self.rdf_type_name = rdf_type_name
        if rdfs_comment is not None:
            self.rdfs_comment = rdfs_comment
        if publisher is not None:
            self.publisher = publisher
        if publication_date is not None:
            self.publication_date = publication_date
        if last_updated_date is not None:
            self.last_updated_date = last_updated_date
        if super_types is not None:
            self.super_types = super_types
        if data_dto is not None:
            self.data_dto = data_dto
        if datafile_dto is not None:
            self.datafile_dto = datafile_dto
        if root_class is not None:
            self.root_class = root_class
        if is_property is not None:
            self.is_property = is_property
        if factor_uri is not None:
            self.factor_uri = factor_uri

    @property
    def uri(self):
        """Gets the uri of this URIGlobalSearchDTO.  # noqa: E501


        :return: The uri of this URIGlobalSearchDTO.  # noqa: E501
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """Sets the uri of this URIGlobalSearchDTO.


        :param uri: The uri of this URIGlobalSearchDTO.  # noqa: E501
        :type: str
        """

        self._uri = uri

    @property
    def name(self):
        """Gets the name of this URIGlobalSearchDTO.  # noqa: E501


        :return: The name of this URIGlobalSearchDTO.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this URIGlobalSearchDTO.


        :param name: The name of this URIGlobalSearchDTO.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def context(self):
        """Gets the context of this URIGlobalSearchDTO.  # noqa: E501


        :return: The context of this URIGlobalSearchDTO.  # noqa: E501
        :rtype: str
        """
        return self._context

    @context.setter
    def context(self, context):
        """Sets the context of this URIGlobalSearchDTO.


        :param context: The context of this URIGlobalSearchDTO.  # noqa: E501
        :type: str
        """

        self._context = context

    @property
    def _property(self):
        """Gets the _property of this URIGlobalSearchDTO.  # noqa: E501


        :return: The _property of this URIGlobalSearchDTO.  # noqa: E501
        :rtype: bool
        """
        return self.__property

    @_property.setter
    def _property(self, _property):
        """Sets the _property of this URIGlobalSearchDTO.


        :param _property: The _property of this URIGlobalSearchDTO.  # noqa: E501
        :type: bool
        """

        self.__property = _property

    @property
    def rdf_type(self):
        """Gets the rdf_type of this URIGlobalSearchDTO.  # noqa: E501


        :return: The rdf_type of this URIGlobalSearchDTO.  # noqa: E501
        :rtype: str
        """
        return self._rdf_type

    @rdf_type.setter
    def rdf_type(self, rdf_type):
        """Sets the rdf_type of this URIGlobalSearchDTO.


        :param rdf_type: The rdf_type of this URIGlobalSearchDTO.  # noqa: E501
        :type: str
        """

        self._rdf_type = rdf_type

    @property
    def rdf_type_name(self):
        """Gets the rdf_type_name of this URIGlobalSearchDTO.  # noqa: E501


        :return: The rdf_type_name of this URIGlobalSearchDTO.  # noqa: E501
        :rtype: str
        """
        return self._rdf_type_name

    @rdf_type_name.setter
    def rdf_type_name(self, rdf_type_name):
        """Sets the rdf_type_name of this URIGlobalSearchDTO.


        :param rdf_type_name: The rdf_type_name of this URIGlobalSearchDTO.  # noqa: E501
        :type: str
        """

        self._rdf_type_name = rdf_type_name

    @property
    def rdfs_comment(self):
        """Gets the rdfs_comment of this URIGlobalSearchDTO.  # noqa: E501


        :return: The rdfs_comment of this URIGlobalSearchDTO.  # noqa: E501
        :rtype: str
        """
        return self._rdfs_comment

    @rdfs_comment.setter
    def rdfs_comment(self, rdfs_comment):
        """Sets the rdfs_comment of this URIGlobalSearchDTO.


        :param rdfs_comment: The rdfs_comment of this URIGlobalSearchDTO.  # noqa: E501
        :type: str
        """

        self._rdfs_comment = rdfs_comment

    @property
    def publisher(self):
        """Gets the publisher of this URIGlobalSearchDTO.  # noqa: E501


        :return: The publisher of this URIGlobalSearchDTO.  # noqa: E501
        :rtype: UserGetDTO
        """
        return self._publisher

    @publisher.setter
    def publisher(self, publisher):
        """Sets the publisher of this URIGlobalSearchDTO.


        :param publisher: The publisher of this URIGlobalSearchDTO.  # noqa: E501
        :type: UserGetDTO
        """

        self._publisher = publisher

    @property
    def publication_date(self):
        """Gets the publication_date of this URIGlobalSearchDTO.  # noqa: E501


        :return: The publication_date of this URIGlobalSearchDTO.  # noqa: E501
        :rtype: str
        """
        return self._publication_date

    @publication_date.setter
    def publication_date(self, publication_date):
        """Sets the publication_date of this URIGlobalSearchDTO.


        :param publication_date: The publication_date of this URIGlobalSearchDTO.  # noqa: E501
        :type: str
        """

        self._publication_date = publication_date

    @property
    def last_updated_date(self):
        """Gets the last_updated_date of this URIGlobalSearchDTO.  # noqa: E501


        :return: The last_updated_date of this URIGlobalSearchDTO.  # noqa: E501
        :rtype: str
        """
        return self._last_updated_date

    @last_updated_date.setter
    def last_updated_date(self, last_updated_date):
        """Sets the last_updated_date of this URIGlobalSearchDTO.


        :param last_updated_date: The last_updated_date of this URIGlobalSearchDTO.  # noqa: E501
        :type: str
        """

        self._last_updated_date = last_updated_date

    @property
    def super_types(self):
        """Gets the super_types of this URIGlobalSearchDTO.  # noqa: E501


        :return: The super_types of this URIGlobalSearchDTO.  # noqa: E501
        :rtype: URITypesDTO
        """
        return self._super_types

    @super_types.setter
    def super_types(self, super_types):
        """Sets the super_types of this URIGlobalSearchDTO.


        :param super_types: The super_types of this URIGlobalSearchDTO.  # noqa: E501
        :type: URITypesDTO
        """

        self._super_types = super_types

    @property
    def data_dto(self):
        """Gets the data_dto of this URIGlobalSearchDTO.  # noqa: E501


        :return: The data_dto of this URIGlobalSearchDTO.  # noqa: E501
        :rtype: DataGetSearchDTO
        """
        return self._data_dto

    @data_dto.setter
    def data_dto(self, data_dto):
        """Sets the data_dto of this URIGlobalSearchDTO.


        :param data_dto: The data_dto of this URIGlobalSearchDTO.  # noqa: E501
        :type: DataGetSearchDTO
        """

        self._data_dto = data_dto

    @property
    def datafile_dto(self):
        """Gets the datafile_dto of this URIGlobalSearchDTO.  # noqa: E501


        :return: The datafile_dto of this URIGlobalSearchDTO.  # noqa: E501
        :rtype: DataFileGetDTO
        """
        return self._datafile_dto

    @datafile_dto.setter
    def datafile_dto(self, datafile_dto):
        """Sets the datafile_dto of this URIGlobalSearchDTO.


        :param datafile_dto: The datafile_dto of this URIGlobalSearchDTO.  # noqa: E501
        :type: DataFileGetDTO
        """

        self._datafile_dto = datafile_dto

    @property
    def root_class(self):
        """Gets the root_class of this URIGlobalSearchDTO.  # noqa: E501


        :return: The root_class of this URIGlobalSearchDTO.  # noqa: E501
        :rtype: str
        """
        return self._root_class

    @root_class.setter
    def root_class(self, root_class):
        """Sets the root_class of this URIGlobalSearchDTO.


        :param root_class: The root_class of this URIGlobalSearchDTO.  # noqa: E501
        :type: str
        """

        self._root_class = root_class

    @property
    def is_property(self):
        """Gets the is_property of this URIGlobalSearchDTO.  # noqa: E501


        :return: The is_property of this URIGlobalSearchDTO.  # noqa: E501
        :rtype: bool
        """
        return self._is_property

    @is_property.setter
    def is_property(self, is_property):
        """Sets the is_property of this URIGlobalSearchDTO.


        :param is_property: The is_property of this URIGlobalSearchDTO.  # noqa: E501
        :type: bool
        """

        self._is_property = is_property

    @property
    def factor_uri(self):
        """Gets the factor_uri of this URIGlobalSearchDTO.  # noqa: E501


        :return: The factor_uri of this URIGlobalSearchDTO.  # noqa: E501
        :rtype: str
        """
        return self._factor_uri

    @factor_uri.setter
    def factor_uri(self, factor_uri):
        """Sets the factor_uri of this URIGlobalSearchDTO.


        :param factor_uri: The factor_uri of this URIGlobalSearchDTO.  # noqa: E501
        :type: str
        """

        self._factor_uri = factor_uri

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(URIGlobalSearchDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_api_formated_dict(self):
        """Returns a dict of properties as named in the API rather than in the model itself"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[self.attribute_map[attr]] = list(map(
                    lambda x: x.to_api_formated_dict() if hasattr(x, "to_api_formated_dict") else x,
                    value
                ))
            elif hasattr(value, "to_api_formated_dict"):
                result[self.attribute_map[attr]] = value.to_api_formated_dict()
            elif isinstance(value, dict):
                result[self.attribute_map[attr]] = dict(map(
                    lambda item: (item[0], item[1].to_api_formated_dict())
                    if hasattr(item[1], "to_api_formated_dict") else item,
                    value.items()
                ))
            else:
                result[self.attribute_map[attr]] = value
        if issubclass(URIGlobalSearchDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, URIGlobalSearchDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
 

        
